server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:pricesDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console